type: gas-bot
name: Currency Converter
logo: https://static.thenounproject.com/png/2318541-200.png
scriptId: 1KPU60slDZBVslJdt9EnKx-3irpgXfdai30-g0cdyuSaILvHRfYBLTnVu
clientId: 321364005933-28d88ahs0ltmpkvvmq57oclaitakmpq8.apps.googleusercontent.com
scopes: "https://www.googleapis.com/auth/script.external_request"
apiVersion: v2
triggers: onTransactionPosted
deploymentId: MKAgiUnECvm5nh0soueQaCpNuZToV6OsP