name: Exchange Bot
logo: https://static.thenounproject.com/png/2318541-200.png
scriptId: 1KPU60slDZBVslJdt9EnKx-3irpgXfdai30-g0cdyuSaILvHRfYBLTnVu
menuUrl: https://script.google.com/macros/s/AKfycbxI7OU_cMGfqX6FqsCoLrQrTrFGlZ3SNwajwMNBqR8YBdCpJjI/exec?bookId=${book.id}
menuText: Exchange Gain/Loss update
menuPopupWidth: 400,
menuPopupHeight: 300,
clientId: 321364005933-28d88ahs0ltmpkvvmq57oclaitakmpq8.apps.googleusercontent.com
scopes: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/script.external_request
apiVersion: v2
triggers: onTransactionPosted
deploymentId: AKfycbxz1Fl1A_KpvAtWLSXtGh1oRaFdWibPweoJfa3yYrFRAAC6gRM
whitelist: >
    maelcaldas@gmail.com
    ppvbkper@ppvbooks.com.uy
    jacobvdb@gmail.com
    esper.raquel@gmail.com
    cpreve@brain.uy
    dgcotelo@gmail.com
    lgarcia@ppv.com.uy
    jherrera@pvci.com.uy
    brainbkper@ppvbooks.com.uy